## 1. Análise Exploratória de Dados (EDA)
 Nesta etapa, exploramos a estrutura dos arquivos da CVM para identificar inconsistências, valores nulos e entender a distribuição das contas contábeis. Esta análise orienta as decisões de limpeza que virão a seguir.

In [1]:
import pandas as pd
import numpy as np

### 1.1 Carregamento dos dados

In [2]:
df_dre = pd.read_csv(
    "dfp_cia_aberta_DRE_con_2024.csv",
    sep=";",
    encoding="ISO-8859-1"
)

df_bpa = pd.read_csv(
    "dfp_cia_aberta_BPA_con_2024.csv",
    sep=";",
    encoding="ISO-8859-1"
)

df_bpp = pd.read_csv(
    "dfp_cia_aberta_BPP_con_2024.csv",
    sep=";",
    encoding="ISO-8859-1"
)

### 1.2 Inspeção estrutural dos datasets

In [3]:
df_dre.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2023-01-01,2023-12-31,3.01,Receitas de Intermediação Financeira,265438605.0,S
1,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.01,Receitas de Intermediação Financeira,273505274.0,S
2,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2023-01-01,2023-12-31,3.01.01,Receita de Juros,265438605.0,N
3,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2024-01-01,2024-12-31,3.01.01,Receita de Juros,273505274.0,N
4,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2023-01-01,2023-12-31,3.02,Despesas de Intermediação Financeira,-176689874.0,S

In [4]:
df_bpa.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2023-12-31,1,Ativo Total,2.153878e+09,S
1,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-12-31,1,Ativo Total,2.398719e+09,S
2,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2023-12-31,1.01,Caixa e Equivalentes de Caixa,5.699981e+07,S
3,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2024-12-31,1.01,Caixa e Equivalentes de Caixa,8.316724e+07,S
4,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2023-12-31,1.01.01,Caixa,1.732774e+07,S

In [5]:
df_bpp.head()

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,PENÚLTIMO,2023-12-31,2,Passivo Total,2.153878e+09,S
1,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-12-31,2,Passivo Total,2.398719e+09,S
2,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,PENÚLTIMO,2023-12-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,2.509742e+06,S
3,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2024-12-31,2.01,Passivos Financeiros Avaliados ao Valor Justo ...,8.266681e+06,S
4,00.000.000/0001-91,2024-12-31,1,BCO BRASIL S.A.,1023,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,PENÚLTIMO,2023-12-31,2.02,Passivos Financeiros ao Custo Amortizado,1.884405e+09,S

### 1.3 Qualidade dos dados

In [6]:
datasets = {
    "DRE": df_dre,
    "BPA": df_bpa,
    "BPP": df_bpp
}

for nome, df in datasets.items():

    print(f"\n===== {nome} =====")

    # Visão inicial
    print("\nShape:")
    print(df.shape)

    print("\nInfo:")
    df.info()

    # Estatísticas básicas
    print("\nDescribe:")
    print(df.describe())

    # Valores nulos
    print("\nValores nulos:")
    print(df.isna().sum())

    # Empresas únicas
    print("\nEmpresas únicas (CNPJ):")
    print(df['CNPJ_CIA'].nunique())

    # Escala monetária
    print("\nEscala de moeda:")
    print(df['ESCALA_MOEDA'].unique())

    # Duplicados
    print("\nRegistros duplicados:")
    print(df.duplicated().sum())

    # Contas contábeis mais frequentes (se existir)
    if 'DS_CONTA' in df.columns:
        print("\nContas contábeis mais frequentes:")
        print(df['DS_CONTA'].value_counts().head(10))

===== DRE =====

Shape:
(32652, 15)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32652 entries, 0 to 32651
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CNPJ_CIA       32652 non-null  object
 1   DT_REFER       32652 non-null  object
 2   VERSAO         32652 non-null  int64
 3   DENOM_CIA      32652 non-null  object
 4   CD_CVM         32652 non-null  int64
 5   GRUPO_DFP      32652 non-null  object
 6   MOEDA          32652 non-null  object
 7   ESCALA_MOEDA   32652 non-null  object
 8   ORDEM_EXERC    32652 non-null  object
 9   DT_INI_EXERC   32652 non-null  object
 10  DT_FIM_EXERC   32652 non-null  object
 11  CD_CONTA       32652 non-null  object
 12  DS_CONTA       32652 non-null  object
 13  VL_CONTA       32652 non-null  float64
 14  ST_CONTA_FIXA  32652 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 3.7+ MB

Describe:
             VERSAO        CD_CVM      VL_CONTA
count  32652.000000  32652.000000  3.265200e+04
mean       1.267916  20313.487076  5.637571e+05
std        0.526190   9753.060765  3.800238e+07
min        1.000000     94.000000 -1.126441e+09
25%        1.000000  16101.000000 -2.848225e+04
50%        1.000000  22020.000000  0.000000e+00
75%        1.000000  25720.000000  8.067500e+03
max        4.000000  80233.000000  2.577113e+09

Valores nulos:
CNPJ_CIA         0
DT_REFER         0
VERSAO           0
DENOM_CIA        0
CD_CVM           0
GRUPO_DFP        0
MOEDA            0
ESCALA_MOEDA     0
ORDEM_EXERC      0
DT_INI_EXERC     0
DT_FIM_EXERC     0
CD_CONTA         0
DS_CONTA         0
VL_CONTA         0
ST_CONTA_FIXA    0
dtype: int64

Empresas únicas (CNPJ):
465

Escala de moeda:
['MIL' 'UNIDADE']

Registros duplicados:
128

Contas contábeis mais frequentes:
DS_CONTA
ON                                   1568
Outras Despesas Operacionais         1002
Receitas Financeiras                  996
Despesas Financeiras                  992
Outras Receitas Operacionais          976
Despesas Gerais e Administrativas     948
Lucro Básico por Ação                 934
Corrente                              934
Lucro Diluído por Ação                934
Diferido                              934
Name: count, dtype: int64

===== BPA =====

Shape:
(62440, 14)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62440 entries, 0 to 62439
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CNPJ_CIA       62440 non-null  object
 1   DT_REFER       62440 non-null  object
 2   VERSAO         62440 non-null  int64
 3   DENOM_CIA      62440 non-null  object
 4   CD_CVM         62440 non-null  int64
 5   GRUPO_DFP      62440 non-null  object
 6   MOEDA          62440 non-null  object
 7   ESCALA_MOEDA   62440 non-null  object
 8   ORDEM_EXERC    62440 non-null  object
 9   DT_FIM_EXERC   62440 non-null  object
 10  CD_CONTA       62440 non-null  object
 11  DS_CONTA       62440 non-null  object
 12  VL_CONTA       62440 non-null  float64
 13  ST_CONTA_FIXA  62440 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 6.7+ MB

Describe:
             VERSAO        CD_CVM      VL_CONTA
count  62440.000000  62440.000000  6.244000e+04
mean       1.267040  20599.147598  3.779242e+06
std        0.524139   9430.414501  7.754858e+07
min        1.000000     94.000000 -5.013874e+07
25%        1.000000  16705.000000  0.000000e+00
50%        1.000000  22586.000000  0.000000e+00
75%        1.000000  25798.000000  1.266048e+05
max        4.000000  80233.000000  4.663343e+09

Valores nulos:
CNPJ_CIA         0
DT_REFER         0
VERSAO           0
DENOM_CIA        0
CD_CVM           0
GRUPO_DFP        0
MOEDA            0
ESCALA_MOEDA     0
ORDEM_EXERC      0
DT_FIM_EXERC     0
CD_CONTA         0
DS_CONTA         0
VL_CONTA         0
ST_CONTA_FIXA    0
dtype: int64

Empresas únicas (CNPJ):
465

Escala de moeda:
['MIL' 'UNIDADE']

Registros duplicados:
256

Contas contábeis mais frequentes:
DS_CONTA
Despesas Antecipadas                                                                       1842
Outras Contas a Receber                                                                    1836
Ativos de Operações Descontinuadas                                                         1836
Contas a Receber                                                                           1832
Estoques                                                                                   1822
Títulos Designados a Valor Justo                                                           1814
Aplicações Financeiras Avaliadas ao Custo Amortizado                                       1810
Aplicações Financeiras Avaliadas a Valor Justo através do Resultado                        1810
Aplicações Financeiras Avaliadas a Valor Justo através de Outros Resultados Abrangentes    1800
Ativos Biológicos                                                                          1796
Name: count, dtype: int64

===== BPP =====

Shape:
(106650, 14)

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106650 entries, 0 to 106649
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   CNPJ_CIA       106650 non-null  object
 1   DT_REFER       106650 non-null  object
 2   VERSAO         106650 non-null  int64
 3   DENOM_CIA      106650 non-null  object
 4   CD_CVM         106650 non-null  int64
 5   GRUPO_DFP      106650 non-null  object
 6   MOEDA          106650 non-null  object
 7   ESCALA_MOEDA   106650 non-null  object
 8   ORDEM_EXERC    106650 non-null  object
 9   DT_FIM_EXERC   106650 non-null  object
 10  CD_CONTA       106650 non-null  object
 11  DS_CONTA       106650 non-null  object
 12  VL_CONTA       106650 non-null  float64
 13  ST_CONTA_FIXA  106650 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 11.4+ MB

Describe:
             VERSAO         CD_CVM      VL_CONTA
count  106650.00000  106650.000000  1.066500e+05
mean        1.26136   20642.433211  1.912055e+06
std         0.52082    9343.058686  4.983436e+07
min         1.00000      94.000000 -7.787804e+07
25%         1.00000   16993.000000  0.000000e+00
50%         1.00000   22608.000000  0.000000e+00
75%         1.00000   25801.000000  3.300100e+04
max         4.00000   80233.000000  4.665290e+09

Valores nulos:
CNPJ_CIA         0
DT_REFER         0
VERSAO           0
DENOM_CIA        0
CD_CVM           0
GRUPO_DFP        0
MOEDA            0
ESCALA_MOEDA     0
ORDEM_EXERC      0
DT_FIM_EXERC     0
CD_CONTA         0
DS_CONTA         0
VL_CONTA         0
ST_CONTA_FIXA    0
dtype: int64

Empresas únicas (CNPJ):
465

Escala de moeda:
['MIL' 'UNIDADE']

Registros duplicados:
456

Contas contábeis mais frequentes:
DS_CONTA
Empréstimos e Financiamentos                               3594
Outros                                                     2008
Outras Obrigações                                          1932
Debêntures                                                 1898
Ações em Tesouraria                                        1874
Provisões                                                  1858
Outras Provisões                                           1848
Passivos sobre Ativos de Operações Descontinuadas          1834
Financiamento por Arrendamento                             1810
Provisões Fiscais Previdenciárias Trabalhistas e Cíveis    1804
Name: count, dtype: int64

### 1.4 Identificação das contas contábeis

In [7]:
df_dre[['CD_CONTA', 'DS_CONTA']].drop_duplicates().sort_values('CD_CONTA')

         CD_CONTA                                           DS_CONTA
0            3.01               Receitas de Intermediação Financeira
15500        3.01  Receitas das Atividades Seguradoras/Ressegurad...
126          3.01             Receita de Venda de Bens e/ou Serviços
15082        3.01               Receitas da Intermediação Financeira
15502     3.01.01                               Receitas com Seguros
...           ...                                                ...
1190   3.99.02.02                                                 PN
1586   3.99.02.02                                                 ON
258    3.99.02.02                                                PNA
260    3.99.02.03                                                PNB
14468  3.99.02.04                                                PNC

[1793 rows x 2 columns]

In [8]:
df_dre[df_dre['DS_CONTA'].str.contains("receita", case=False, na=False)][['CD_CONTA','DS_CONTA']].drop_duplicates()

      CD_CONTA                                           DS_CONTA
0         3.01               Receitas de Intermediação Financeira
2      3.01.01                                   Receita de Juros
10        3.04            Outras Despesas e Receitas Operacionais
14     3.04.02                  Receitas de Prestação de Serviços
22     3.04.06                       Outras Receitas Operacionais
...        ...                                                ...
32030  3.01.08                                    Outras Receitas
32054  3.01.20                                    Outras Receitas
32120  3.01.01          Receita líquida com vendas de mercadorias
32122  3.01.02  Receita líquida com produtos e serviços financ...
32388  3.01.01        Receita liquida de incorporação imobiliária

[227 rows x 2 columns]

In [9]:
df_dre[df_dre['DS_CONTA'].str.contains("resultado", case=False, na=False)][['CD_CONTA','DS_CONTA']].drop_duplicates()

         CD_CONTA                                           DS_CONTA
8            3.03        Resultado Bruto de Intermediação Financeira
26     3.04.06.02  Resultado líquido em operações de câmbio e em ...
40        3.04.08              Resultado da Equivalência Patrimonial
42           3.05         Resultado antes dos Tributos sobre o Lucro
52           3.08     Resultado Líquido das Operações Descontinuadas
...           ...                                                ...
31256  3.04.05.02           Resultado Adesão Parcelamentos Especiais
31328  3.04.04.07  Resultado na alienação de ativos não classific...
31330  3.04.04.08  Resultado na alienação e despesas com ativos n...
31800  3.04.04.04  Resultado em operações com empresas controlada...
31934     3.01.02  Resultado de Variação Cambial de Ativos e Pass...

[124 rows x 2 columns]

In [10]:
df_bpa[['CD_CONTA','DS_CONTA']].drop_duplicates().sort_values('CD_CONTA')

         CD_CONTA                       DS_CONTA
0               1                    Ativo Total
2            1.01  Caixa e Equivalentes de Caixa
166          1.01               Ativo Circulante
4         1.01.01                          Caixa
168       1.01.01  Caixa e Equivalentes de Caixa
...           ...                            ...
76        1.07.01                    Intangíveis
78        1.07.02                       Goodwill
80        1.07.03          Amortização Acumulada
35762  1.07.03.01          Amortização Acumulada
35764  1.07.03.02          Perdas por Impairment

[3472 rows x 2 columns]

In [11]:
df_bpp[['CD_CONTA','DS_CONTA']].drop_duplicates().sort_values('CD_CONTA')

      CD_CONTA                                           DS_CONTA
0            2                                      Passivo Total
2         2.01  Passivos Financeiros Avaliados ao Valor Justo ...
160       2.01                                 Passivo Circulante
50356     2.01  Passivos Financeiros ao Valor Justo através do...
88606  2.01.01               Instrumentos financeiros derivativos
...        ...                                                ...
50422  2.08.05                        Lucros/Prejuízos Acumulados
50424  2.08.06                   Ajustes de Avaliação Patrimonial
50426  2.08.07                    Ajustes Acumulados de Conversão
50428  2.08.08                      Outros Resultados Abrangentes
50430  2.08.09      Participação dos Acionistas Não Controladores

[5479 rows x 2 columns]

In [12]:
datasets = {
    "DRE": df_dre,
    "BPA": df_bpa,
    "BPP": df_bpp
}

for nome, df in datasets.items():

    print(f"\n===== {nome} =====")

    # Distribuição da escala monetária
    print("\nDistribuição da escala monetária:")
    print(df['ESCALA_MOEDA'].value_counts())

    # Tipos de exercício contábil (se existir)
    if 'ORDEM_EXERC' in df.columns:
        print("\nOrdem do exercício:")
        print(df['ORDEM_EXERC'].value_counts())

===== DRE =====

Distribuição da escala monetária:
ESCALA_MOEDA
MIL        32102
UNIDADE      550
Name: count, dtype: int64

Ordem do exercício:
ORDEM_EXERC
PENÚLTIMO    16326
ÚLTIMO       16326
Name: count, dtype: int64

===== BPA =====

Distribuição da escala monetária:
ESCALA_MOEDA
MIL        61426
UNIDADE     1014
Name: count, dtype: int64

Ordem do exercício:
ORDEM_EXERC
PENÚLTIMO    31220
ÚLTIMO       31220
Name: count, dtype: int64

===== BPP =====

Distribuição da escala monetária:
ESCALA_MOEDA
MIL        104814
UNIDADE      1836
Name: count, dtype: int64

Ordem do exercício:
ORDEM_EXERC
PENÚLTIMO    53325
ÚLTIMO       53325
Name: count, dtype: int64

## Principais Observações da EDA

A análise exploratória dos dados da CVM revelou alguns aspectos relevantes para o processamento posterior dos datasets:

- Os dados apresentam diferentes **escalas monetárias**, com parte das empresas reportando valores em milhares. Dessa forma, será necessário padronizar os valores financeiros para garantir comparabilidade entre as observações.

- Observou-se a presença de registros relacionados a diferentes **ordens de exercício contábil** (por exemplo, último e penúltimo exercício), o que pode gerar registros duplicados para uma mesma empresa e período. Será necessário definir um critério de filtragem na etapa de limpeza.

- Algumas empresas encontram-se em **recuperação judicial**, o que pode impactar significativamente indicadores financeiros e deve ser considerado na interpretação dos resultados.

- A análise das colunas `CD_CONTA` e `DS_CONTA` permitiu identificar as **contas contábeis relevantes** que serão utilizadas no cálculo dos indicadores financeiros na etapa de transformação dos dados.

Com base nessas observações, serão aplicadas regras de limpeza e transformação no pipeline ETL, incluindo padronização monetária, filtragem de exercícios contábeis e seleção de contas específicas para cálculo dos indicadores.